(() => {
 'use strict';
 const KEY='bit-chubb-days-v1', order=['A','B','C','D'];
 const blank=()=>({next:'A',session:null,history:[],loads:{}});
 function restore(){try{const raw=JSON.parse(localStorage.getItem(KEY));if(!raw||!order.includes(raw.next)||!Array.isArray(raw.history))return blank();return {...blank(),...raw};}catch{return blank();}}
 let state=restore(), view='home', selected=state.session?.workout||state.next, finishing=false;
 const $=(s)=>document.querySelector(s);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
 const nextOf=w=>order[(order.indexOf(w)+1)%4];
 const exerciseImage=(image,name)=>image?`<button type="button" class="exercise-image" data-image="${esc(image)}" data-image-title="${esc(name)}" aria-label="Ampliar ilustração de ${esc(name)}"><img src="${esc(image)}" alt="Ilustração de ${esc(name)}" loading="lazy"></button>`:'';
 const sessionFor=w=>({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,workout:w,startedAt:new Date().toISOString(),completed:WORKOUTS[w].exercises.map(([,n])=>Array(n).fill(false)),loads:WORKOUTS[w].exercises.map(([name])=>state.loads[name]||''),restEnds:{},cardio:{mode:'',minutes:''}});
 function current(){if(!state.session||state.session.workout!==selected){state.session=sessionFor(selected);save();}return state.session;}
 function header(){ $('#next').textContent=`Próximo na sequência: Treino ${state.next}`;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#home').hidden=view!=='home';$('#history').hidden=view!=='history';}
 function render(){header();if(view==='history'){renderHistory();return;}$('#workout-list').innerHTML=order.map(w=>`<button type="button" class="pick ${w===state.next?'current':''} ${w===selected?'selected':''}" data-workout="${w}" aria-pressed="${w===selected}"><strong>${w}</strong><span>${w===state.next?'PRÓXIMO':'VER TREINO'}</span></button>`).join('');const s=current(), workout=WORKOUTS[selected];$('#session').innerHTML=`<div class="session-top"><div><span class="eyebrow">SEU PLANO</span><h2>Treino ${selected}</h2></div><span class="badge">${s.completed.flat().filter(Boolean).length} / ${s.completed.flat().length} séries</span></div>${workout.exercises.map(([name,sets,reps,rest,image],i)=>`<article class="card"><p class="number">EXERCÍCIO ${String(i+1).padStart(2,'0')}</p><h3>${esc(name)}</h3>${exerciseImage(image,name)}<p class="detail"><strong>${sets} séries</strong> · ${esc(reps)} reps/duração · descanso ${rest}s</p><label class="field">Carga usada (kg)<input data-load="${i}" type="text" inputmode="decimal" autocomplete="off" placeholder="Ex.: 20" value="${esc(s.loads[i])}"></label><div class="sets" aria-label="Séries de ${esc(name)}">${Array.from({length:sets},(_,n)=>`<button type="button" class="set ${s.completed[i][n]?'done':''}" data-ex="${i}" data-set="${n}" aria-pressed="${s.completed[i][n]}" aria-label="Série ${n+1} ${s.completed[i][n]?'concluída':'pendente'}">${s.completed[i][n]?'✓':n+1}</button>`).join('')}</div><div class="rest"><button type="button" data-rest="${i}">Descansar ${rest}s</button><span class="timer" data-timer="${i}" aria-live="off"></span></div></article>`).join('')}<article class="card cardio"><p class="number">ÚLTIMA ETAPA</p><h3>Cardio</h3><p class="detail">Tempo planejado: <strong>${workout.cardio.planned}</strong> · intensidade ${workout.cardio.intensity}</p><div class="cardio-grid"><label class="field">Modalidade<select id="mode"><option value="">Selecione</option>${['esteira','bicicleta','elíptico'].map(m=>`<option value="${m}" ${s.cardio.mode===m?'selected':''}>${m[0].toUpperCase()+m.slice(1)}</option>`).join('')}</select></label><label class="field">Tempo realizado (min)<input id="minutes" type="number" min="0" step="0.1" inputmode="decimal" placeholder="Minutos" value="${esc(s.cardio.minutes)}"></label></div><button class="finish" type="button" id="finish">Finalizar treino</button></article>`;tick();}
 function tick(){if(view!=='home'||!state.session)return;document.querySelectorAll('[data-timer]').forEach(el=>{const end=state.session.restEnds[el.dataset.timer],remaining=end?Math.max(0,Math.ceil((end-Date.now())/1000)):0;el.textContent=remaining?`Restam ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`:'';});}
 function renderHistory(){const list=$('#history-list');list.innerHTML=state.history.length?state.history.slice().reverse().map(h=>`<details class="history-entry"><summary>Treino ${esc(h.workout)} · ${new Date(h.finishedAt).toLocaleString('pt-BR')}</summary><p>Cardio: ${h.cardio.mode?esc(h.cardio.mode):'não informado'} · ${h.cardio.minutes!==''?esc(h.cardio.minutes)+' min':'tempo não informado'}</p><p>Séries marcadas: ${h.completed.flat().filter(Boolean).length}/${h.completed.flat().length}</p><ul>${WORKOUTS[h.workout].exercises.map(([name],i)=>`<li>${esc(name)}: ${h.completed[i].filter(Boolean).length}/${h.completed[i].length} séries · carga ${h.loads[i]!==''?esc(h.loads[i])+' kg':'não informada'}</li>`).join('')}</ul></details>`).join(''):'<p class="muted">Nenhum treino finalizado ainda.</p>';}
 document.addEventListener('click',e=>{const imageButton=e.target.closest('[data-image]');if(imageButton){const dialog=$('#exercise-dialog'),img=$('#dialog-image'),title=$('#dialog-title');img.src=imageButton.dataset.image;img.alt=`Ilustração de ${imageButton.dataset.imageTitle}`;title.textContent=imageButton.dataset.imageTitle;dialog.showModal();return;}if(e.target.closest('.dialog-close')){$('#exercise-dialog').close();return;}const nav=e.target.closest('[data-view]');if(nav){view=nav.dataset.view;render();return;}const pick=e.target.closest('[data-workout]');if(pick){selected=pick.dataset.workout;render();return;}const set=e.target.closest('[data-set]');if(set){const s=current(),i=+set.dataset.ex,n=+set.dataset.set;s.completed[i][n]=!s.completed[i][n];save();render();return;}const rest=e.target.closest('[data-rest]');if(rest){const s=current(),i=+rest.dataset.rest;s.restEnds[i]=Date.now()+WORKOUTS[selected].exercises[i][3]*1000;save();tick();return;}if(e.target.id==='finish'){if(finishing)return;finishing=true;const s=state.session;if(!s||s.workout!==selected){finishing=false;return;}const button=$('#finish');button.disabled=true;try{if(!state.history.some(h=>h.id===s.id)){state.history.push({...s,finishedAt:new Date().toISOString()});state.next=nextOf(s.workout);state.session=null;save();}selected=state.next;render();window.scrollTo({top:0,behavior:'smooth'});}catch(err){button.disabled=false;alert('Não foi possível salvar o treino neste dispositivo. Verifique o espaço disponível.');}finally{finishing=false;}}});
 document.addEventListener('input',e=>{const s=state.session;if(!s)return;if(e.target.matches('[data-load]')){const i=+e.target.dataset.load;s.loads[i]=e.target.value;state.loads[WORKOUTS[s.workout].exercises[i][0]]=e.target.value;save();}if(e.target.id==='minutes'){s.cardio.minutes=e.target.value;save();}});
 document.addEventListener('change',e=>{if(e.target.id==='mode'&&state.session){state.session.cardio.mode=e.target.value;save();}});
 $('#exercise-dialog').addEventListener('click',e=>{if(e.target.id==='exercise-dialog')e.currentTarget.close();});
 document.addEventListener('visibilitychange',tick);setInterval(tick,1000);render();
 if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
 window.BitChubbDebug={nextOf,restore,read:()=>state};
})();
