// Plano fornecido pelo usuário. Ordem, séries, repetições e pausas são fixas.
window.WORKOUTS = Object.freeze({
 A:{cardio:{planned:'20–25 minutos',intensity:'moderada'},exercises:[
 ['Supino inclinado com halteres',3,'8–12',90,'assets/exercises/supino-inclinado.png'],['Supino reto máquina/barra',3,'8–12',90,'assets/exercises/supino-reto.png'],['Cross polia alta → baixa',2,'12–15',60,'assets/exercises/cross-alta-baixa.png'],['Puxada frontal',3,'8–12',90,'assets/exercises/puxada-frontal.png'],['Remada baixa sentada',3,'10–12',75,'assets/exercises/remada-baixa.png'],['Elevação lateral',3,'12–15',60,'assets/exercises/elevacao-lateral.png'],['Rosca martelo',3,'10–12',60,'assets/exercises/rosca-martelo.png'],['Tríceps unilateral no cross',3,'10–15',60,'assets/exercises/triceps-unilateral-cross.png']]},
 B:{cardio:{planned:'10–15 minutos',intensity:'leve'},exercises:[
 ['Agachamento no Smith',3,'8–12',120,'assets/exercises/agachamento-smith.png'],['Leg press 45°',3,'10–15',90,'assets/exercises/leg-press-45.png'],['Cadeira extensora',2,'12–15',60,'assets/exercises/cadeira-extensora.png'],['Elevação pélvica',3,'8–12',90,'assets/exercises/elevacao-pelvica.png'],['Panturrilha em pé/máquina',3,'12–20',60,'assets/exercises/panturrilha-em-pe.png'],['Rosca Scott',3,'10–12',60,'assets/exercises/rosca-scott.png'],['Rosca inclinada com halteres',2,'10–12',60,'assets/exercises/rosca-inclinada.png'],['Pallof press no cross',3,'10–12 por lado',45,'assets/exercises/pallof-press.png']]},
 C:{cardio:{planned:'20–25 minutos',intensity:'moderada'},exercises:[
 ['Puxada neutra ou aberta',3,'8–12',90,'assets/exercises/puxada-neutra.png'],['Remada articulada',3,'8–12',90,'assets/exercises/remada-articulada.png'],['Pulldown braços estendidos',2,'12–15',60,'assets/exercises/pulldown-bracos-estendidos.png'],['Supino inclinado máquina',3,'8–12',90,'assets/exercises/supino-inclinado-maquina.png'],['Crucifixo/crossover médio',2,'12–15',60,'assets/exercises/crossover-medio.png'],['Desenvolvimento com halteres',3,'8–12',75,'assets/exercises/desenvolvimento-halteres.png'],['Crucifixo invertido',3,'12–15',60,'assets/exercises/crucifixo-invertido.png'],['Tríceps corda',3,'10–15',60,'assets/exercises/triceps-corda.png']]},
 D:{cardio:{planned:'10–15 minutos',intensity:'leve'},exercises:[
 ['Stiff com barra/halteres',3,'8–12',120,'assets/exercises/stiff.png'],['Mesa ou cadeira flexora',3,'10–15',75,'assets/exercises/mesa-flexora.png'],['Afundo no Smith/passada',3,'8–12 por perna',90,'assets/exercises/afundo-smith.png'],['Leg press pés altos',3,'10–15',90,'assets/exercises/leg-press-pes-altos.png'],['Abdutora',3,'15–20',60,'assets/exercises/abdutora.png'],['Panturrilha sentada',3,'12–20',60,'assets/exercises/panturrilha-sentada.png'],['Prancha',3,'30–45 s',45,'assets/exercises/prancha.png'],['Dead bug',2,'8–12 por lado',45,'assets/exercises/dead-bug.png']]}
});
