// Plano fornecido pelo usuário. Ordem, séries, repetições e pausas são fixas.
window.WORKOUTS = Object.freeze({
 A:{cardio:{planned:'20–25 minutos',intensity:'moderada'},exercises:[
 ['Supino inclinado com halteres',3,'8–12',90,'assets/exercises/supino-inclinado.webp'],['Supino reto máquina/barra',3,'8–12',90,'assets/exercises/supino-reto.webp'],['Cross polia alta → baixa',2,'12–15',60,'assets/exercises/cross-alta-baixa.webp'],['Puxada frontal',3,'8–12',90,'assets/exercises/puxada-frontal.webp'],['Remada baixa sentada',3,'10–12',75,'assets/exercises/remada-baixa.webp'],['Elevação lateral',3,'12–15',60,'assets/exercises/elevacao-lateral.webp'],['Rosca martelo',3,'10–12',60,'assets/exercises/rosca-martelo.webp'],['Tríceps unilateral no cross',3,'10–15',60,'assets/exercises/triceps-unilateral-cross.webp']]},
 B:{cardio:{planned:'10–15 minutos',intensity:'leve'},exercises:[
 ['Agachamento no Smith',3,'8–12',120,'assets/exercises/agachamento-smith.svg'],['Leg press 45°',3,'10–15',90,'assets/exercises/leg-press-45.svg'],['Cadeira extensora',2,'12–15',60,'assets/exercises/cadeira-extensora.svg'],['Elevação pélvica',3,'8–12',90,'assets/exercises/elevacao-pelvica.svg'],['Panturrilha em pé/máquina',3,'12–20',60,'assets/exercises/panturrilha-em-pe.svg'],['Rosca Scott',3,'10–12',60,'assets/exercises/rosca-scott.svg'],['Rosca inclinada com halteres',2,'10–12',60,'assets/exercises/rosca-inclinada.svg'],['Pallof press no cross',3,'10–12 por lado',45,'assets/exercises/pallof-press.svg']]},
 C:{cardio:{planned:'20–25 minutos',intensity:'moderada'},exercises:[
 ['Puxada neutra ou aberta',3,'8–12',90,'assets/exercises/puxada-neutra.svg'],['Remada articulada',3,'8–12',90,'assets/exercises/remada-articulada.svg'],['Pulldown braços estendidos',2,'12–15',60,'assets/exercises/pulldown-bracos-estendidos.svg'],['Supino inclinado máquina',3,'8–12',90,'assets/exercises/supino-inclinado-maquina.svg'],['Crucifixo/crossover médio',2,'12–15',60,'assets/exercises/crossover-medio.svg'],['Desenvolvimento com halteres',3,'8–12',75,'assets/exercises/desenvolvimento-halteres.svg'],['Crucifixo invertido',3,'12–15',60,'assets/exercises/crucifixo-invertido.svg'],['Tríceps corda',3,'10–15',60,'assets/exercises/triceps-corda.svg']]},
 D:{cardio:{planned:'10–15 minutos',intensity:'leve'},exercises:[
 ['Stiff com barra/halteres',3,'8–12',120,'assets/exercises/stiff.svg'],['Mesa ou cadeira flexora',3,'10–15',75,'assets/exercises/mesa-flexora.svg'],['Afundo no Smith/passada',3,'8–12 por perna',90,'assets/exercises/afundo-smith.svg'],['Leg press pés altos',3,'10–15',90,'assets/exercises/leg-press-pes-altos.svg'],['Abdutora',3,'15–20',60,'assets/exercises/abdutora.svg'],['Panturrilha sentada',3,'12–20',60,'assets/exercises/panturrilha-sentada.svg'],['Prancha',3,'30–45 s',45,'assets/exercises/prancha.svg'],['Dead bug',2,'8–12 por lado',45,'assets/exercises/dead-bug.svg']]}
});
